afterUTS/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('story9.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'

urlpatterns = [
    path('',views.Homepage, name='Homepage')
]

story9/urls.py
from django.urls import path
from . import views

app_name='story9'

urlpatterns = [
    path('story9/hallo',views.hallo, name='hallo'),
    path('story9/login',views.login_view, name='login_view'),
    path('story9/register',views.register_view, name='register_view'),
    path('story9/logout',views.logout_view, name='logout_view'),
]

homepage/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model

)

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email has already been registered")
        return super(UserRegisterForm, self).clean(*args, **kwargs)

homepage/views.py
from django.shortcuts import render

# Create your views here.
def Homepage(request):
    return render(request, 'homepage.html')

story9/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)
from .forms import UserLoginForm, UserRegisterForm
# Create your views here.

@login_required
def hallo(request):
    return render(request,'hallo.html')


def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('story9:hallo')

    context = {
        'form': form,
    }
    return render(request, "login.html", context)


def register_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('story9:login_view')

    context = {
        'form': form,
    }
    return render(request, "signup.html", context)

def logout_view(request):
    logout(request)
    return redirect('story9:login_view')

homepage/templates/base.html
{% load static %}
<!DOCTYPE HTML>

<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>AFTER UTS</title>
    </head>
<body>
    <!-- Fixed navbar -->
    <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
          <a class="navbar-brand" href="{% url 'homepage:Homepage' %}">After UTS Story</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
              <li class="nav-item"><a class="nav-link" href=#>STORY 6 </a></li>
              <li class="nav-item"><a class="nav-link" href=#>STORY 7 </a></li>
              <li class="nav-item"><a class="nav-link" href=#>STORY 8 </a></li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'story9:hallo' %}">STORY 9 </a></li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'story9:login_view' %}">STORY 9 </a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" href=#>STORY 10 </a></li>
            </ul>
          </div>
        </div>
      </nav>

    {% block page_content %}
    {% endblock %}

    <footer>
      <div class ="footer-border"  >
        <p class="text-footer">I'm so fuckin' tired </p>
      </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

homepage/templates/homepage.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="font-weight-light">Welcome to After UTS Story</h1>
        <p class="lead">A compilation of PPW stories after mid-exam</p>
      </div>
    </div>
  </div>
</header>
{% endblock %}

story9/templates/hallo.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="font-weight-light">Hallo, {{ user.get_username }}!</h1>
        <a class="btn btn-primary" href="{% url 'story9:logout_view' %}">Logout</a>
      </div>
    </div>
  </div>
</header>
{% endblock %}

story9/templates/login.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <form action="" method="POST" class="all-form">
          {% csrf_token %}
          <h1 class="font-weight-light">Please login first</h1>
          <div class="form-group">
            <label>Username</label>
            {{ form.username}}
          </div>
          <div class="form-group">
            <label>Password</label>
            {{ form.password}}
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
          <h6>if you don't have account, please register
          <a href="{% url 'story9:register_view' %}"> here</a></h6>
        </form>
      </div>
    </div>
  </div>
</header>
{% endblock %}

story9/templates/signup.html
{% extends "base.html" %}

{% load static %}
{% block page_content %}
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center form-column outer-form">
        <form action="" method="POST" class="all-form">
          {% csrf_token %}
          <h1 class="font-weight-light">Register Your Account</h1>
          <div class="form-group">
            <label>Username          </label>
            {{ form.username}}
          </div>
          <div class="form-group">
            <label>Email             </label>
            {{ form.email}}
          </div>
          <div class="form-group">
            <label>Confirm Your Email</label>
            {{ form.email2}}
          </div>
          <div class="form-group">
            <label>Password          </label>
            {{ form.password}}
          </div>
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
      </div>
    </div>
  </div>
</header>
{% endblock %}